### ISSUE TITLE
Returns `inventory url` instead of `job_templates url` for the GET request of the job_template.

### ISSUE THREAD

**Issue by IsuruDilhan** [pearsonappeng/tensor#4]
`GET http://{{url}}/v1/job_templates/587dd64261c9a90001051cb7/ `
Returns,
`{
"url": "/v1/inventories/587dd64261c9a90001051cb7/"
}`
But it should be,
`{
"url": "/v1/job_templates/587dd64261c9a90001051cb7/"
}`

**Comment by singhabahu** [comment]
This is fixed in this commit [3de1894](https://github.com/pearsonappeng/tensor/commit/3de189443f3809af8f902841559ebc15d919b13d), I think we can close this issue after merging with the master branch.
